services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: ai-incident-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: incident_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: